library(tidyverse)
library(tidymodels)
library(data.table)

dat <- readRDS(file = "BoxscoreData20230210.RDS") %>% data.table()

dat <- dat[MP != "Did Not Play"]

timeFields <- "MP"
dateFields <- "GameDate"
numericFields <- c('FG',
                   'FGA',
                   'FG%',
                   '3P',
                   '3PA',
                   '3P%',
                   'FT',
                   'FTA',
                   'FT%',
                   'ORB',
                   'DRB',
                   'TRB',
                   'AST',
                   'STL',
                   'BLK',
                   'TOV',
                   'PF',
                   'PTS',
                   '+/-',
                   'TS%',
                   'eFG%',
                   '3PAr',
                   'FTr',
                   'ORB%',
                   'DRB%',
                   'TRB%',
                   'AST%',
                   'STL%',
                   'BLK%',
                   'TOV%',
                   'USG%',
                   'ORtg',
                   'DRtg',
                   'BPM')

factorFields <- names(dat) %>% setdiff(c(timeFields, dateFields, numericFields))

# dat[, (timeFields) := lapply(.SD,  lubridate::ms), .SDcols = timeFields]
dat[, (dateFields) := lapply(.SD,  lubridate::as_date), .SDcols = dateFields]
dat[, (numericFields) := lapply(.SD,  as.numeric), .SDcols = numericFields]
dat[, (factorFields) := lapply(.SD,  as.factor), .SDcols = factorFields]

dat[, c("Minutes", "Seconds") := tstrsplit(MP, split = ":", fixed = TRUE)]
dat[, Minutes := as.numeric(Minutes)]
dat[, Seconds := as.numeric(Seconds)]
dat[, MinutesPlayed := Minutes + Seconds / 60] %>% 
  .[, c("MP", "Minutes", "Seconds") := NULL]

dat <- dat[!is.na(MinutesPlayed)]
dat[, `FG%` := FG / FGA]
dat[, `3P%` := `3P` / `3PA`]
dat[, `FT%` := FT / FTA]

setnames(
  dat,
  old = c(
    'Player',
    'FG',
    'FGA',
    'FG%',
    '3P',
    '3PA',
    '3P%',
    'FT',
    'FTA',
    'FT%',
    'ORB',
    'DRB',
    'TRB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS',
    '+/-',
    'Team',
    'Location',
    'Opponent',
    'GameDate',
    'TS%',
    'eFG%',
    '3PAr',
    'FTr',
    'ORB%',
    'DRB%',
    'TRB%',
    'AST%',
    'STL%',
    'BLK%',
    'TOV%',
    'USG%',
    'ORtg',
    'DRtg',
    'BPM',
    'MinutesPlayed'
  ),
  new = c(
    'Player',
    'FieldGoalsMade',
    'FieldGoalsAttempted',
    'FieldGoalsPercentage',
    'ThreePointersMade',
    'ThreePointersAttempted',
    'ThreePointersPercentage',
    'FreeThrowsMade',
    'FreeThrowsAttempted',
    'FreeThrowsPercentage',
    'OffensiveRebounds',
    'DefensiveRebounds',
    'TotalRebounds',
    'Assists',
    'Steals',
    'Blocks',
    'Turnovers',
    'PersonalFouls',
    'Points',
    'PlusMinus',
    'Team',
    'Location',
    'Opponent',
    'GameDate',
    'TrueShootingPercentage',
    'EffectiveFieldGoalPercentage',
    'ThreePointAttemptRate',
    'FreeThrowAttemptRate',
    'OffensiveReboundPercentage',
    'DefensiveReboundPercentage',
    'TotalReboundPercentage',
    'AssistPercentage',
    'StealPercentage',
    'BlockPercentage',
    'TurnoverPercentage',
    'UsagePercentage',
    'OffensiveRating',
    'DefensiveRating',
    'BoxPlusMinus',
    'MinutesPlayed'
  ) 
)

setorder(dat, Team, Player, GameDate)

dat[,`:=` (
  Points3 = frollsum(Points, n = 3, align = "right"),
  Points5 = frollsum(Points, n = 5, align = "right"),
  Points10 = frollsum(Points, n = 10, align = "right"),
  TotalPointsToDate = cumsum(Points),
  FieldGoalsMade3 = frollsum(FieldGoalsMade, n = 3, align = "right"),
  FieldGoalsMade5 = frollsum(FieldGoalsMade, n = 5, align = "right"),
  FieldGoalsMade10 = frollsum(FieldGoalsMade, n = 10, align = "right"),
  TotalFieldGoalsMadeToDate = cumsum(FieldGoalsMade),
  FieldGoalsAttempted3 = frollsum(FieldGoalsAttempted, n = 3, align = "right"),
  FieldGoalsAttempted5 = frollsum(FieldGoalsAttempted, n = 5, align = "right"),
  FieldGoalsAttempted10 = frollsum(FieldGoalsAttempted, n = 10, align = "right"),
  TotalFieldGoalsAttemptedToDate = cumsum(FieldGoalsAttempted),
  ThreePointersMade3 = frollsum(ThreePointersMade, n = 3, align = "right"),
  ThreePointersMade5 = frollsum(ThreePointersMade, n = 5, align = "right"),
  ThreePointersMade10 = frollsum(ThreePointersMade, n = 10, align = "right"),
  TotalThreePointersMadeToDate = cumsum(ThreePointersMade),
  ThreePointersAttempted3 = frollsum(ThreePointersAttempted, n = 3, align = "right"),
  ThreePointersAttempted5 = frollsum(ThreePointersAttempted, n = 5, align = "right"),
  ThreePointersAttempted10 = frollsum(ThreePointersAttempted, n = 10, align = "right"),
  TotalThreePointersAttemptedToDate = cumsum(ThreePointersAttempted),
  FreeThrowsMade3 = frollsum(FreeThrowsMade, n = 3, align = "right"),
  FreeThrowsMade5 = frollsum(FreeThrowsMade, n = 5, align = "right"),
  FreeThrowsMade10 = frollsum(FreeThrowsMade, n = 10, align = "right"),
  TotalFreeThrowsMadeToDate = cumsum(FreeThrowsMade),
  FreeThrowsAttempted3 = frollsum(FreeThrowsAttempted, n = 3, align = "right"),
  FreeThrowsAttempted5 = frollsum(FreeThrowsAttempted, n = 5, align = "right"),
  FreeThrowsAttempted10 = frollsum(FreeThrowsAttempted, n = 10, align = "right"),
  TotalFreeThrowsAttemptedToDate = cumsum(FreeThrowsAttempted),
  OffensiveRebounds3 = frollsum(OffensiveRebounds, n = 3, align = "right"),
  OffensiveRebounds5 = frollsum(OffensiveRebounds, n = 5, align = "right"),
  OffensiveRebounds10 = frollsum(OffensiveRebounds, n = 10, align = "right"),
  TotalOffensiveReboundsToDate = cumsum(OffensiveRebounds),
  DefensiveRebounds3 = frollsum(DefensiveRebounds, n = 3, align = "right"),
  DefensiveRebounds5 = frollsum(DefensiveRebounds, n = 5, align = "right"),
  DefensiveRebounds10 = frollsum(DefensiveRebounds, n = 10, align = "right"),
  TotalDefensiveReboundsToDate = cumsum(DefensiveRebounds),
  Assists3 = frollsum(Assists, n = 3, align = "right"),
  Assists5 = frollsum(Assists, n = 5, align = "right"),
  Assists10 = frollsum(Assists, n = 10, align = "right"),
  TotalAssistsToDate = cumsum(Assists),
  Steals3 = frollsum(Steals, n = 3, align = "right"),
  Steals5 = frollsum(Steals, n = 5, align = "right"),
  Steals10 = frollsum(Steals, n = 10, align = "right"),
  TotalStealsToDate = cumsum(Steals),
  Blocks3 = frollsum(Blocks, n = 3, align = "right"),
  Blocks5 = frollsum(Blocks, n = 5, align = "right"),
  Blocks10 = frollsum(Blocks, n = 10, align = "right"),
  TotalBlocksToDate = cumsum(Blocks),
  Turnovers3 = frollsum(Turnovers, n = 3, align = "right"),
  Turnovers5 = frollsum(Turnovers, n = 5, align = "right"),
  Turnovers10 = frollsum(Turnovers, n = 10, align = "right"),
  TotalTurnoversToDate = cumsum(Turnovers),
  PersonalFouls3 = frollsum(PersonalFouls, n = 3, align = "right"),
  PersonalFouls5 = frollsum(PersonalFouls, n = 5, align = "right"),
  PersonalFouls10 = frollsum(PersonalFouls, n = 10, align = "right"),
  TotalPersonalFoulsToDate = cumsum(PersonalFouls),
  MinutesPlayed3 = frollsum(MinutesPlayed, n = 3, align = "right"),
  MinutesPlayed5 = frollsum(MinutesPlayed, n = 5, align = "right"),
  MinutesPlayed10 = frollsum(MinutesPlayed, n = 10, align = "right"),
  TotalMinutesPlayedToDate = cumsum(MinutesPlayed)
),
.(Player)]

dat[,`:=` (
  TeamPoints3 = frollsum(Points, n = 3, align = "right"),
  TeamPoints5 = frollsum(Points, n = 5, align = "right"),
  TeamPoints10 = frollsum(Points, n = 10, align = "right"),
  TeamTotalPointsToDate = cumsum(Points),
  TeamFieldGoalsMade3 = frollsum(FieldGoalsMade, n = 3, align = "right"),
  TeamFieldGoalsMade5 = frollsum(FieldGoalsMade, n = 5, align = "right"),
  TeamFieldGoalsMade10 = frollsum(FieldGoalsMade, n = 10, align = "right"),
  TeamTotalFieldGoalsMadeToDate = cumsum(FieldGoalsMade),
  TeamFieldGoalsAttempted3 = frollsum(FieldGoalsAttempted, n = 3, align = "right"),
  TeamFieldGoalsAttempted5 = frollsum(FieldGoalsAttempted, n = 5, align = "right"),
  TeamFieldGoalsAttempted10 = frollsum(FieldGoalsAttempted, n = 10, align = "right"),
  TeamTotalFieldGoalsAttemptedToDate = cumsum(FieldGoalsAttempted),
  TeamThreePointersMade3 = frollsum(ThreePointersMade, n = 3, align = "right"),
  TeamThreePointersMade5 = frollsum(ThreePointersMade, n = 5, align = "right"),
  TeamThreePointersMade10 = frollsum(ThreePointersMade, n = 10, align = "right"),
  TeamTotalThreePointersMadeToDate = cumsum(ThreePointersMade),
  TeamThreePointersAttempted3 = frollsum(ThreePointersAttempted, n = 3, align = "right"),
  TeamThreePointersAttempted5 = frollsum(ThreePointersAttempted, n = 5, align = "right"),
  TeamThreePointersAttempted10 = frollsum(ThreePointersAttempted, n = 10, align = "right"),
  TeamTotalThreePointersAttemptedToDate = cumsum(ThreePointersAttempted),
  TeamFreeThrowsMade3 = frollsum(FreeThrowsMade, n = 3, align = "right"),
  TeamFreeThrowsMade5 = frollsum(FreeThrowsMade, n = 5, align = "right"),
  TeamFreeThrowsMade10 = frollsum(FreeThrowsMade, n = 10, align = "right"),
  TeamTotalFreeThrowsMadeToDate = cumsum(FreeThrowsMade),
  TeamFreeThrowsAttempted3 = frollsum(FreeThrowsAttempted, n = 3, align = "right"),
  TeamFreeThrowsAttempted5 = frollsum(FreeThrowsAttempted, n = 5, align = "right"),
  TeamFreeThrowsAttempted10 = frollsum(FreeThrowsAttempted, n = 10, align = "right"),
  TeamTotalFreeThrowsAttemptedToDate = cumsum(FreeThrowsAttempted),
  TeamOffensiveRebounds3 = frollsum(OffensiveRebounds, n = 3, align = "right"),
  TeamOffensiveRebounds5 = frollsum(OffensiveRebounds, n = 5, align = "right"),
  TeamOffensiveRebounds10 = frollsum(OffensiveRebounds, n = 10, align = "right"),
  TeamTotalOffensiveReboundsToDate = cumsum(OffensiveRebounds),
  TeamDefensiveRebounds3 = frollsum(DefensiveRebounds, n = 3, align = "right"),
  TeamDefensiveRebounds5 = frollsum(DefensiveRebounds, n = 5, align = "right"),
  TeamDefensiveRebounds10 = frollsum(DefensiveRebounds, n = 10, align = "right"),
  TeamTotalDefensiveReboundsToDate = cumsum(DefensiveRebounds),
  TeamAssists3 = frollsum(Assists, n = 3, align = "right"),
  TeamAssists5 = frollsum(Assists, n = 5, align = "right"),
  TeamAssists10 = frollsum(Assists, n = 10, align = "right"),
  TeamTotalAssistsToDate = cumsum(Assists),
  TeamSteals3 = frollsum(Steals, n = 3, align = "right"),
  TeamSteals5 = frollsum(Steals, n = 5, align = "right"),
  TeamSteals10 = frollsum(Steals, n = 10, align = "right"),
  TeamTotalStealsToDate = cumsum(Steals),
  TeamBlocks3 = frollsum(Blocks, n = 3, align = "right"),
  TeamBlocks5 = frollsum(Blocks, n = 5, align = "right"),
  TeamBlocks10 = frollsum(Blocks, n = 10, align = "right"),
  TeamTotalBlocksToDate = cumsum(Blocks),
  TeamTurnovers3 = frollsum(Turnovers, n = 3, align = "right"),
  TeamTurnovers5 = frollsum(Turnovers, n = 5, align = "right"),
  TeamTurnovers10 = frollsum(Turnovers, n = 10, align = "right"),
  TeamTotalTurnoversToDate = cumsum(Turnovers),
  TeamPersonalFouls3 = frollsum(PersonalFouls, n = 3, align = "right"),
  TeamPersonalFouls5 = frollsum(PersonalFouls, n = 5, align = "right"),
  TeamPersonalFouls10 = frollsum(PersonalFouls, n = 10, align = "right"),
  TeamTotalPersonalFoulsToDate = cumsum(PersonalFouls),
  TeamMinutesPlayed3 = frollsum(MinutesPlayed, n = 3, align = "right"),
  TeamMinutesPlayed5 = frollsum(MinutesPlayed, n = 5, align = "right"),
  TeamMinutesPlayed10 = frollsum(MinutesPlayed, n = 10, align = "right"),
  TeamTotalMinutesPlayedToDate = cumsum(MinutesPlayed)
),
.(Team)]

dat[,`:=` (
  OpponentPoints3 = frollsum(Points, n = 3, align = "right"),
  OpponentPoints5 = frollsum(Points, n = 5, align = "right"),
  OpponentPoints10 = frollsum(Points, n = 10, align = "right"),
  OpponentTotalPointsToDate = cumsum(Points),
  OpponentFieldGoalsMade3 = frollsum(FieldGoalsMade, n = 3, align = "right"),
  OpponentFieldGoalsMade5 = frollsum(FieldGoalsMade, n = 5, align = "right"),
  OpponentFieldGoalsMade10 = frollsum(FieldGoalsMade, n = 10, align = "right"),
  OpponentTotalFieldGoalsMadeToDate = cumsum(FieldGoalsMade),
  OpponentFieldGoalsAttempted3 = frollsum(FieldGoalsAttempted, n = 3, align = "right"),
  OpponentFieldGoalsAttempted5 = frollsum(FieldGoalsAttempted, n = 5, align = "right"),
  OpponentFieldGoalsAttempted10 = frollsum(FieldGoalsAttempted, n = 10, align = "right"),
  OpponentTotalFieldGoalsAttemptedToDate = cumsum(FieldGoalsAttempted),
  OpponentThreePointersMade3 = frollsum(ThreePointersMade, n = 3, align = "right"),
  OpponentThreePointersMade5 = frollsum(ThreePointersMade, n = 5, align = "right"),
  OpponentThreePointersMade10 = frollsum(ThreePointersMade, n = 10, align = "right"),
  OpponentTotalThreePointersMadeToDate = cumsum(ThreePointersMade),
  OpponentThreePointersAttempted3 = frollsum(ThreePointersAttempted, n = 3, align = "right"),
  OpponentThreePointersAttempted5 = frollsum(ThreePointersAttempted, n = 5, align = "right"),
  OpponentThreePointersAttempted10 = frollsum(ThreePointersAttempted, n = 10, align = "right"),
  OpponentTotalThreePointersAttemptedToDate = cumsum(ThreePointersAttempted),
  OpponentFreeThrowsMade3 = frollsum(FreeThrowsMade, n = 3, align = "right"),
  OpponentFreeThrowsMade5 = frollsum(FreeThrowsMade, n = 5, align = "right"),
  OpponentFreeThrowsMade10 = frollsum(FreeThrowsMade, n = 10, align = "right"),
  OpponentTotalFreeThrowsMadeToDate = cumsum(FreeThrowsMade),
  OpponentFreeThrowsAttempted3 = frollsum(FreeThrowsAttempted, n = 3, align = "right"),
  OpponentFreeThrowsAttempted5 = frollsum(FreeThrowsAttempted, n = 5, align = "right"),
  OpponentFreeThrowsAttempted10 = frollsum(FreeThrowsAttempted, n = 10, align = "right"),
  OpponentTotalFreeThrowsAttemptedToDate = cumsum(FreeThrowsAttempted),
  OpponentOffensiveRebounds3 = frollsum(OffensiveRebounds, n = 3, align = "right"),
  OpponentOffensiveRebounds5 = frollsum(OffensiveRebounds, n = 5, align = "right"),
  OpponentOffensiveRebounds10 = frollsum(OffensiveRebounds, n = 10, align = "right"),
  OpponentTotalOffensiveReboundsToDate = cumsum(OffensiveRebounds),
  OpponentDefensiveRebounds3 = frollsum(DefensiveRebounds, n = 3, align = "right"),
  OpponentDefensiveRebounds5 = frollsum(DefensiveRebounds, n = 5, align = "right"),
  OpponentDefensiveRebounds10 = frollsum(DefensiveRebounds, n = 10, align = "right"),
  OpponentTotalDefensiveReboundsToDate = cumsum(DefensiveRebounds),
  OpponentAssists3 = frollsum(Assists, n = 3, align = "right"),
  OpponentAssists5 = frollsum(Assists, n = 5, align = "right"),
  OpponentAssists10 = frollsum(Assists, n = 10, align = "right"),
  OpponentTotalAssistsToDate = cumsum(Assists),
  OpponentSteals3 = frollsum(Steals, n = 3, align = "right"),
  OpponentSteals5 = frollsum(Steals, n = 5, align = "right"),
  OpponentSteals10 = frollsum(Steals, n = 10, align = "right"),
  OpponentTotalStealsToDate = cumsum(Steals),
  OpponentBlocks3 = frollsum(Blocks, n = 3, align = "right"),
  OpponentBlocks5 = frollsum(Blocks, n = 5, align = "right"),
  OpponentBlocks10 = frollsum(Blocks, n = 10, align = "right"),
  OpponentTotalBlocksToDate = cumsum(Blocks),
  OpponentTurnovers3 = frollsum(Turnovers, n = 3, align = "right"),
  OpponentTurnovers5 = frollsum(Turnovers, n = 5, align = "right"),
  OpponentTurnovers10 = frollsum(Turnovers, n = 10, align = "right"),
  OpponentTotalTurnoversToDate = cumsum(Turnovers),
  OpponentPersonalFouls3 = frollsum(PersonalFouls, n = 3, align = "right"),
  OpponentPersonalFouls5 = frollsum(PersonalFouls, n = 5, align = "right"),
  OpponentPersonalFouls10 = frollsum(PersonalFouls, n = 10, align = "right"),
  OpponentTotalPersonalFoulsToDate = cumsum(PersonalFouls),
  OpponentMinutesPlayed3 = frollsum(MinutesPlayed, n = 3, align = "right"),
  OpponentMinutesPlayed5 = frollsum(MinutesPlayed, n = 5, align = "right"),
  OpponentMinutesPlayed10 = frollsum(MinutesPlayed, n = 10, align = "right"),
  OpponentTotalMinutesPlayedToDate = cumsum(MinutesPlayed)
),
.(Opponent)]

dat[1:120] %>% view
